# Generated by Django 4.2.11 on 2026-02-27 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_block_commentlike_conversation_follow_like_message_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(max_length=350, unique=True)),
                (
                    "announcement_type",
                    models.CharField(
                        choices=[
                            ("notice", "📢 Notice"),
                            ("event", "🎉 Event"),
                            ("news", "📰 News"),
                            ("academic", "📚 Academic"),
                            ("exam", "📝 Exam Schedule"),
                            ("result", "📊 Result"),
                            ("holiday", "🎪 Holiday"),
                            ("emergency", "🚨 Emergency"),
                        ],
                        default="notice",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="Brief summary for cards", max_length=500
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="announcements/featured/"
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="announcements/attachments/"
                    ),
                ),
                ("external_link", models.URLField(blank=True, null=True)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("general", "🌍 General - Everyone"),
                            ("students", "👥 All Students"),
                            ("faculty", "👨\u200d🏫 Faculty Only"),
                            ("staff", "👔 Staff Only"),
                            ("department", "🏛️ Specific Department"),
                            ("batch", "🎓 Specific Batch"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "target_batch",
                    models.CharField(
                        blank=True, help_text="e.g., 2024, 2023, etc.", max_length=20
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("event_start_date", models.DateTimeField(blank=True, null=True)),
                ("event_end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="For submissions, registrations, etc.",
                        null=True,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                ("is_virtual", models.BooleanField(default=False)),
                ("meeting_link", models.URLField(blank=True, null=True)),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_important", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("comments_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_pinned", "-published_at"],
            },
        ),
        migrations.CreateModel(
            name="AnnouncementCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(default="fas fa-bullhorn", max_length=50)),
                ("color", models.CharField(default="indigo-600", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Announcement Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(default="fas fa-building", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AnnouncementComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("is_approved", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="core.announcement",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="core.announcementcomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcement_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnnouncementAuthorPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_create_general",
                    models.BooleanField(
                        default=False, help_text="Can create general announcements"
                    ),
                ),
                (
                    "can_create_departmental",
                    models.BooleanField(
                        default=False, help_text="Can create departmental announcements"
                    ),
                ),
                ("can_create_events", models.BooleanField(default=False)),
                ("can_create_notices", models.BooleanField(default=False)),
                ("can_create_news", models.BooleanField(default=False)),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "departments",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Which departments they can post for",
                        related_name="authorized_users",
                        to="core.department",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcement_permission",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="announcement",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="announcements",
                to="core.announcementcategory",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="announcements",
                to="core.department",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="target_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="targeted_announcements",
                to="core.department",
            ),
        ),
        migrations.CreateModel(
            name="AnnouncementView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="core.announcement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "announcement")},
            },
        ),
        migrations.CreateModel(
            name="AnnouncementLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="core.announcement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcement_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "announcement")},
            },
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["-published_at"], name="core_announ_publish_7530c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["announcement_type"], name="core_announ_announc_80af62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["audience"], name="core_announ_audienc_5d46b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["department"], name="core_announ_departm_42383d_idx"
            ),
        ),
    ]
