# Generated by Django 4.2.11 on 2026-02-27 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_announcement_announcementcategory_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="batch",
            field=models.CharField(
                blank=True, help_text="e.g., 2024, 2023, etc.", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="core.department",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="student_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="university",
            field=models.CharField(
                blank=True, default="Campus University", max_length=200
            ),
        ),
    ]
