# Generated by Django 4.2.11 on 2026-02-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_profile_batch_profile_department_profile_student_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcementcomment",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
    ]