# Generated by Django 4.2.11 on 2026-03-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_announcementcomment_is_edited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("follow", "New Follower"),
                    ("like", "Post Like"),
                    ("comment", "New Comment"),
                    ("reply", "Comment Reply"),
                    ("share", "Post Share"),
                    ("mention", "Mention"),
                    ("friend_request", "Friend Request"),
                    ("friend_accept", "Friend Request Accepted"),
                    ("birthday", "Birthday"),
                    ("post", "New Post"),
                    ("report", "User Report"),
                ],
                max_length=20,
            ),
        ),
    ]
