# Generated by Django 4.2.11 on 2026-03-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="reason",
            field=models.CharField(
                choices=[
                    ("spam", "Spam"),
                    ("harassment", "Harassment"),
                    ("nudity", "Nudity"),
                    ("violence", "Violence"),
                    ("hate_speech", "Hate Speech"),
                    ("fake", "Fake Account"),
                    ("inappropriate", "Inappropriate Content"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("post", "Post"),
                    ("comment", "Comment"),
                    ("user", "User"),
                    ("message", "Message"),
                ],
                max_length=10,
            ),
        ),
    ]
