# Generated by Django 4.2.11 on 2026-03-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_contactmessage_user_alter_contactmessage_replied_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_verification_otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_verification_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="profile",
            name="student_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
