# Generated by Django 4.2.11 on 2026-03-06 21:32

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_fix_student_id_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='student_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]