# Generated by Django 4.2.11 on 2026-03-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_add_student_id_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="student_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
