# Generated by Django 4.2.11 on 2026-03-09 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_announcement_slug_alter_profile_student_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="post_documents/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "pdf",
                            "doc",
                            "docx",
                            "txt",
                            "ppt",
                            "pptx",
                            "xls",
                            "xlsx",
                            "csv",
                            "zip",
                            "rar",
                        ]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="post_videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["mp4", "mov", "avi", "webm", "mkv"]
                    )
                ],
            ),
        ),
    ]
