# Generated by Django 5.2.12 on 2026-04-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_post_document_alter_post_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="file_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="is_file",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="is_image",
            field=models.BooleanField(default=False),
        ),
    ]
