# Generated by Django 5.2.12 on 2026-04-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_message_file_name_message_file_url_message_is_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="file_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
