# Generated by Django 5.2.12 on 2026-04-11 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_message_file_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-is_pinned", "-created_at"]},
        ),
    ]
