# Generated by Django 5.2.12 on 2026-04-14 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_post_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="shared_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shared_messages",
                to="core.post",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="shared_post_preview",
            field=models.TextField(blank=True, null=True),
        ),
    ]
